//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Morph.RC
//
#define IDI_ICON1                       101
#define IDR_ACCELERATOR1                103
#define IDI_ICON2                       110
#define CMD_KEY_LEFT                    40001
#define CMD_KEY_RIGHT                   40002
#define CMD_KEY_UP                      40003
#define CMD_KEY_DOWN                    40004
#define CMD_SHIFT_KEY_x                 40005
#define CMD_KEY_x                       40006
#define CMD_KEY_1                       40007
#define CMD_KEY_2                       40008
#define CMD_KEY_3                       40009
#define CMD_KEY_4                       40010
#define CMD_KEY_5                       40011
#define CMD_KEY_6                       40012
#define CMD_KEY_7                       40013
#define CMD_KEY_8                       40014
#define CMD_KEY_9                       40015
#define CMD_KEY_0                       40016
#define CMD_SHIFT_KEY_a                 40017
#define CMD_KEY_a                       40018
#define CMD_SHIFT_KEY_s                 40019
#define CMD_KEY_s                       40020
#define CMD_KEY_d                       40021
#define CMD_KEY_f                       40022
#define CMD_SHIFT_KEY_g                 40023
#define CMD_KEY_g                       40024
#define CMD_SHIFT_KEY_j                 40025
#define CMD_KEY_j                       40026
#define CMD_SHIFT_KEY_h                 40028
#define CMD_KEY_h                       40029
#define CMD_SHIFT_KEY_k                 40030
#define CMD_KEY_k                       40031
#define CMD_SHIFT_KEY_l                 40032
#define CMD_KEY_l                       40033
#define CMD_KEY_z                       40034
#define CMD_KEY_q                       40035
#define CMD_KEY_w                       40036
#define CMD_KEY_e                       40037
#define CMD_KEY_r                       40038
#define CMD_KEY_t                       40039
#define CMD_KEY_y                       40040
#define CMD_KEY_RETURN                  40041
#define CMD_KEY_ESCAPE                  40042
#define CMD_KEY_SPACE                   40043

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         40043
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
